### ISSUE TITLE
Error: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#30]
Hi,

Just trying tangata and I am getting some errors in the console. The website is loading but the catalog is empty.
FYI, I am running it in Windows Subsystem for Linux.

```
[2021-06-17 12:13:57,087] ERROR in app: Exception on /api/v1/model_tree [GET]
Traceback (most recent call last):
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata.py", line 45, in model_tree
    return tangata_api.get_model_tree()
  File "/home/xxxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_api.py", line 130, in get_model_tree
    resultObject = reduce(merge_models, split_models)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by ciejer** [comment]
Thanks - second person today that's shared it - I believe I know what is going wrong and will have a fix in tonight

**Comment by ciejer** [comment]
Should be fixed - seems to be a difference between py3.6 and 3.8 (I hope, my venv's aren't working so couldn't verify error).
Can you please try again after upgrading to 0.1.9?

**Comment by b-per** [comment]
So, the new version was still failing but I managed to get the website running with the following changes:
- In `tangata_api`: There was an error with `global`. I had to move`global skipDBTCompile` in `def reload_dbt(sendToast):` by putting it just as the first line of the function
- In `tangata_catalog_compile`: 
  - I replaced `git_bin.execute('git log --numstat --pretty=format:"\t\t\t%H\t%h\t%at\t%aN\t%s"')` (which was raising an error) by `git_bin.execute(['git', 'log',  '--numstat', '--pretty=format:"\t\t\t%H\t%h\t%at\t%aN\t%s"'])`
  - I replaced `if lineTabs[0] == '' and lineTabs[1] == '':` by `if (lineTabs[0] == '' or lineTabs[0] == '"') and lineTabs[1] == '':` ; in my case, `lineTabs[0]`'s value is `'"'` and not just `''`

After those changes the website loads and I can see my models. I have not tested changing anything yet.

**Comment by ciejer** [comment]
Have made above changes, confirmed it still runs in windows - 0.1.10 pushed to pypi.  
`global` issue was created by yesterday's fix - highlighted a gap in my testing.  
`tangata_catalog_compile` is unix compatibility, all makes sense - I'll get a WSL env spun up in the next few days to add to testing for new versions
Thanks very much for this!

**Comment by b-per** [comment]
0.1.10 is now working without any modification on my part. I have other errors but I'll raise a different issue.
