### ISSUE TITLE
tags are applied to all models instead of just the selected model

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#37]
Hi.

I am not sure if I misunderstand the `tags` capabilities of tangata, but when I added a tag, it added it in my `dbt_project.yml`, and applied it to all my models. I would have thought that a tag defined on a specific model would only apply to this model.

**Comment by ciejer** [comment]
You certainly did not misinterpret that - I noticed some weird behaviour in tags the other day and it's likely related.
Seems to have been introduced in the python port - will have a look at this before the new features

**Comment by ciejer** [comment]
Have changed tag writing behaviour - haven't recreated exact issue, can you please confirm this is fixed on your setup with 0.1.12?

**Comment by b-per** [comment]
Hi, The issue is still here in `0.1.12`.

The tag gets added here in `dbt_project.yml`:
```
models:
  my_project:
    marts:
      +materialized: table
    curated:
      +schema: curated
    staging:
      +schema: staging

    tags:
      - my_tangata_tag
```

**Comment by ciejer** [comment]
Same cause as #41 - turns out unix paths are just better.
